### ISSUE TITLE
Failed to load external module @babel/register

### ISSUE THREAD

**Issue by unikneeraj** [UltimateAngular/ultimate-angular-master-seed#5]
Hi Todd,
Thanks for this Great course!  
I'm facing a "Failed to load external module @babel/register" error when run the "npm start" command.
Node Version: v8.11.3
Npm Version: 6.3.0
Gulp version:  3.9.1

```
[22:42:35] Failed to load external module @babel/register
[22:42:35] Requiring external module babel-register
/Users/neerkumar/Downloads/Learnings/ContactApp/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                              ^^^^^^
SyntaxError: Unexpected token import   
     at createScript (vm.js:80:10)   
    at Object.runInThisContext (vm.js:139:10)    
   at Module._compile (module.js:616:28)   
   at loader (/Users/neerkumar/Downloads/Learnings/ContactApp/node_modules/babel-register/lib/node.js:144:5)   
  at Object.require.extensions.(anonymous function) [as .js] (/Users/neerkumar/Downloads/Learnings/ContactApp/node_modules/babel-regi
ster/lib/node.js:154:7)   
 at Module.load (module.js:565:32)   
 at tryModuleLoad (module.js:505:12)    
at Function.Module._load (module.js:497:3)    
at Module.require (module.js:596:17)    
at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contacts@1.0.0 start: `gulp`
npm ERR! Exit status 1npm ERR!
npm ERR! Failed at the contacts@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/neerkumar/.npm/_logs/2018-08-07T17_12_35_510Z-debug.log

```

Thanks in advance.

**Comment by unikneeraj** [comment]
Issue has been fixed by downgrading the gulp version to  3.9.0.
